## Capstone: Car Accident Severity 

## Introduction | Business Undertanding
In an effort to reduce the frequency of car collisions in a community, an algorithim must be developed to predict the severity of an accident given the current weather, road and visibility conditions. When conditions are bad, this model will alert drivers to remind them to be more careful.

## Data Understanding
Our predictor or target variable will be 'SEVERITYCODE' because it is used measure the severity of an accident from 0 to 5 within the dataset. Attributes used to weigh the severity of an accident are 'WEATHER'and'ROADCOND'.

## Data
The features used will be: • SEVERITYCODE  • WEATHER • ROADCOND

The data used for this study is given by the Applied Data Science Capstone course on Coursera.org via the following link https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv.

In [1]:
import pandas as pd


## Import and view data

In [2]:
df=pd.read_csv("C:\py19\Data-Collisions (2).csv")
df


C:\Users\taran\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
0                  2 -122.323148  47.703140         1    1307       1307   
1                  1 -122.347294  47.647172         2   52200      52200   
2                  1 -122.334540  47.607871         3   26700      26700   
3                  1 -122.334803  47.604803         4    1144       1144   
4                  2 -122.306426  47.545739         5   17700      17700   
...              ...         ...        ...       ...     ...        ...   
194668             2 -122.290826  47.565408    219543  309534     310814   
194669             1 -122.344526  47.690924    219544  309085     310365   
194670             2 -122.306689  47.683047    219545  311280     312640   
194671             2 -122.355317  47.678734    219546  309514     310794   
194672             1 -122.289360  47.611017    219547  308220     309500   

       REPORTNO   STATUS      ADDRTYPE   INTKEY  ... ROADCOND  \
0       3502005  Matched  Intersection  37475.0  ...      Wet   
1       2607959  Matched         Block      NaN  ...      Wet   
2       1482393  Matched         Block      NaN  ...      Dry   
3       3503937  Matched         Block      NaN  ...      Dry   
4       1807429  Matched  Intersection  34387.0  ...      Wet   
...         ...      ...           ...      ...  ...      ...   
194668  E871089  Matched         Block      NaN  ...      Dry   
194669  E876731  Matched         Block      NaN  ...      Wet   
194670  3809984  Matched  Intersection  24760.0  ...      Dry   
194671  3810083  Matched  Intersection  24349.0  ...      Dry   
194672  E868008  Matched         Block      NaN  ...      Wet   

                      LIGHTCOND PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0                      Daylight           NaN         NaN      NaN         10   
1       Dark - Street Lights On           NaN   6354039.0      NaN         11   
2                      Daylight           NaN   4323031.0      NaN         32   
3                      Daylight           NaN         NaN      NaN         23   
4                      Daylight           NaN   4028032.0      NaN         10   
...                         ...           ...         ...      ...        ...   
194668                 Daylight           NaN         NaN      NaN         24   
194669                 Daylight           NaN         NaN      NaN         13   
194670                 Daylight           NaN         NaN      NaN         28   
194671                     Dusk           NaN         NaN      NaN          5   
194672                 Daylight           NaN         NaN      NaN         14   

                                               ST_COLDESC  SEGLANEKEY  \
0                                       Entering at angle           0   
1       From same direction - both going straight - bo...           0   
2                                  One parked--one moving           0   
3                        From same direction - all others           0   
4                                       Entering at angle           0   
...                                                   ...         ...   
194668    From opposite direction - both moving - head-on           0   
194669  From same direction - both going straight - bo...           0   
194670  From opposite direction - one left turn - one ...           0   
194671                       Vehicle Strikes Pedalcyclist        4308   
194672  From same direction - both going straight - on...           0   

        CROSSWALKKEY  HITPARKEDCAR  
0                  0             N  
1                  0             N  
2                  0             N  
3                  0             N  
4                  0             N  
...              ...           ...  
194668             0             N  
194669             0             N  
194670             0             N  
194671             0             N  
194672             0             N  

[194673 rows x 38 c

In [3]:
df.shape

(194673, 38)

In [4]:
df.columns

Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')

In [3]:
print(df.dtypes)

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: objec

In [4]:
data=df[['WEATHER','ROADCOND','SEVERITYCODE']]
data

WEATHER ROADCOND  SEVERITYCODE
0       Overcast      Wet             2
1        Raining      Wet             1
2       Overcast      Dry             1
3          Clear      Dry             1
4        Raining      Wet             2
...          ...      ...           ...
194668     Clear      Dry             2
194669   Raining      Wet             1
194670     Clear      Dry             2
194671     Clear      Dry             2
194672     Clear      Wet             1

[194673 rows x 3 columns]

In [5]:
inputs=data.drop('SEVERITYCODE',axis='columns')
target = df['SEVERITYCODE']


In [6]:
inputs['WEATHER']=inputs['WEATHER'].fillna(0)
inputs['ROADCOND']=inputs['ROADCOND'].fillna(0)

inputs

WEATHER ROADCOND
0       Overcast      Wet
1        Raining      Wet
2       Overcast      Dry
3          Clear      Dry
4        Raining      Wet
...          ...      ...
194668     Clear      Dry
194669   Raining      Wet
194670     Clear      Dry
194671     Clear      Dry
194672     Clear      Wet

[194673 rows x 2 columns]

In [7]:
target

0         2
1         1
2         1
3         1
4         2
         ..
194668    2
194669    1
194670    2
194671    2
194672    1
Name: SEVERITYCODE, Length: 194673, dtype: int64

In [8]:
inputs['weather1']=pd.factorize(inputs.WEATHER)[0]
inputs['ROAD']=pd.factorize(inputs.ROADCOND)[0]
#inputs['LIGHTCOND1']=pd.factorize(inputs.LIGHTCOND)[0]

In [9]:
inputs.head(17)

WEATHER ROADCOND  weather1  ROAD
0   Overcast      Wet         0     0
1    Raining      Wet         1     0
2   Overcast      Dry         0     1
3      Clear      Dry         2     1
4    Raining      Wet         1     0
5      Clear      Dry         2     1
6    Raining      Wet         1     0
7      Clear      Dry         2     1
8      Clear      Dry         2     1
9      Clear      Dry         2     1
10  Overcast      Dry         0     1
11     Clear      Dry         2     1
12   Raining      Wet         1     0
13   Raining      Wet         1     0
14     Clear      Dry         2     1
15         0        0         3     2
16  Overcast      Dry         0     1

In [10]:
inputs_n=inputs.drop(['WEATHER', 'ROADCOND'], axis='columns')

In [11]:
inputs_n

weather1  ROAD
0              0     0
1              1     0
2              0     1
3              2     1
4              1     0
...          ...   ...
194668         2     1
194669         1     0
194670         2     1
194671         2     1
194672         2     0

[194673 rows x 2 columns]

In [12]:
import numpy as np
x=np.asarray(inputs_n[['weather1','ROAD']])

In [13]:
x[0:5]

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 1],
       [1, 0]], dtype=int64)

In [14]:
y=np.asarray(target)

In [15]:
y

array([2, 1, 1, ..., 2, 2, 1], dtype=int64)

In [16]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [17]:
model.fit(inputs_n, target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
model.score(inputs_n,target)

0.7011449969949608

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [24]:
print('Train set:', X_train.shape,  y_train.shape)
print(' test:', X_test.shape,  y_test.shape)

Train set: (130430, 2) (130430,)
 test: (64243, 2) (64243,)


In [26]:
print('Train set:', X_train)

Train set: [[2 1]
 [0 1]
 [6 5]
 ...
 [2 1]
 [2 1]
 [0 1]]


## Methodology
Our data is now ready to be fed into machine learning models.

We will use the following models:

## K-Nearest Neighbor (KNN)
KNN will help us predict the severity code of an outcome by finding the most similar to data point within k distance.

### K-Nearest Neighbors (KNN)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
k=25

In [36]:
neigh=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
neigh
kyhat=neigh.predict(X_test)
kyhat

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

### Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier
colDataTree = DecisionTreeClassifier(criterion="entropy",max_depth =7)
colDataTree
colDataTree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [44]:
Dyhat = colDataTree.predict(X_test)
print(Dyhat[0:5])
print(y_test[0:5])

[1 1 1 1 1]
[2 1 2 2 1]


### Logistic Regression

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
LRyhat =LR.predict(X_test)
LRyhat[0:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [49]:
yhat_prob =LR.predict_proba(X_test)
yhat_prob

array([[0.67115665, 0.32884335],
       [0.83833563, 0.16166437],
       [0.70839969, 0.29160031],
       ...,
       [0.62445209, 0.37554791],
       [0.67115665, 0.32884335],
       [0.62445209, 0.37554791]])